#!/usr/bin/env python
"""
Session 7 — score your handoff assertions.

You do not edit this file. You edit my_handoffs7.py, which has a worked
example at the top and two rows (HW-001 and HW-003) with TODOs in them.
This script reads that file and scores whatever it finds there.

Runs each row you wrote assertions for through two pipelines:

    healthy        nothing injected
    lost_handoff   the diagnostics tail is stripped on its way out

and prints what your assertion did in each. The verdict you want is
DISCRIMINATING: pass on healthy, fail on broken.

    DISCRIMINATING  pass / fail   your assertion measures something
    DECORATIVE      pass / pass   it survives the break, so it cannot fail
    WRONG           fail / fail   it is false about the healthy system too
    INVERTED        fail / pass   look at this one; something is odd

No API key needed and nothing is spent: this runs the deterministic stub.
"""

from __future__ import annotations

import sys

import coord_eval7
import seeds7~
from delegation_rows7 import BY_ID
from my_handoffs7 import MY_HANDOFFS
from plant_agents7 import run_pipeline

VERDICTS = {(1, 0): "DISCRIMINATING", (1, 1): "DECORATIVE",
            (0, 0): "WRONG", (0, 1): "INVERTED"}


def screen(row_id: str, spec: dict) -> dict:
    row = dict(BY_ID[row_id])
    facts = {k: v for k, v in (spec.get("facts") or {}).items() if v}
    row["handoff_facts"] = facts

    out = {}
    for seed in ("healthy", "lost_handoff"):
        res = run_pipeline(row["request"], impl="stub", seed=seeds7.get(seed))
        out[seed] = coord_eval7.handoff_integrity(res, row)
    pair = (out["healthy"]["score"], out["lost_handoff"]["score"])
    return {"row_id": row_id, "n_facts": sum(len(v) for v in facts.values()),
            "verdict": VERDICTS[pair], "healthy": out["healthy"],
            "broken": out["lost_handoff"], "predict": (spec.get("predict") or "").strip()}


def main() -> int:
    if not MY_HANDOFFS:
        print("my_handoffs7.py is empty."); return 1

    empty = [rid for rid, s in MY_HANDOFFS.items()
             if not any((s.get("facts") or {}).values())]
    if empty:
        print(f"No facts written for: {', '.join(empty)}. Open my_handoffs7.py "
              f"and fill in the TODOs.")
        if len(empty) == len(MY_HANDOFFS):
            return 1

    results = []
    for rid, spec in MY_HANDOFFS.items():
        if not any((spec.get("facts") or {}).values()):
            continue
        r = screen(rid, spec)
        results.append(r)
        print(f"\n{rid}  {r['n_facts']} fact(s) -> {r['verdict']}")
        print(f"  healthy : {'pass' if r['healthy']['score'] else 'FAIL'}  "
              f"{r['healthy']['comment']}")
        print(f"  broken  : {'pass' if r['broken']['score'] else 'FAIL'}  "
              f"{r['broken']['comment']}")
        if not r["predict"]:
            # Session 5, harness bug #6: an empty prediction scored as a HIT
            # and handed every untouched TODO a perfect score. Not again.
            print("  predict : EMPTY — not scored. A prediction you did not "
                  "write cannot be wrong, which is why it is worth nothing.")
        else:
            print(f"  predict : {r['predict']}")

    disc = sum(1 for r in results if r["verdict"] == "DISCRIMINATING")
    print(f"\n{disc}/{len(results)} of your assertions discriminate.")
    if disc < len(results):
        print("An assertion that passes both runs is not a weak test. It is "
              "not a test. Ask what the receiving agent could NOT have known "
              "any other way, and assert on that.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
