#!/usr/bin/env python
"""
Session 7 — score your handoff assertions.

You do not edit this file. You edit my_handoffs7.py, which has a worked
example at the top and two rows (HW-001 and HW-003) with TODOs in them.
This script reads that file and scores whatever it finds there.

Runs each row you wrote assertions for through two pipelines:

    healthy        nothing injected
    lost_handoff   the diagnostics tail is stripped on its way out

and prints what your assertion did in each. The verdict you want is
DISCRIMINATING: pass on healthy, fail on broken.

    DISCRIMINATING  pass / fail   your assertion measures something
    DECORATIVE      pass / pass   it survives the break, so it cannot fail
    WRONG           fail / fail   it is false about the healthy system too
    INVERTED        fail / pass   look at this one; something is odd

No API key needed and nothing is spent: this runs the deterministic stub.
"""

from __future__ import annotations


import _path  # noqa: F401  -- puts shared/ and plant/ on sys.path; must be first
import sys

import coord_eval7
import seeds7
from delegation_rows7 import BY_ID
from my_handoffs7 import MY_HANDOFFS
from plant_agents7 import run_pipeline

VERDICTS = {(1, 0): "DISCRIMINATING", (1, 1): "DECORATIVE",
            (0, 0): "WRONG", (0, 1): "INVERTED"}


def screen_edge(row_id: str, edge: str, facts: list) -> dict:
    """Screen ONE edge against the seed that actually breaks THAT edge.

    FIXED AFTER SESSION 7. This used to run every assertion against
    `lost_handoff`, which strips the tail on diagnostics -> documentation and
    nowhere else. An assertion on documentation -> maintenance therefore could
    not fail, and came back DECORATIVE by construction -- a property of this
    screener, not of the student's assertion. It made HW-005 a partly decorative
    exercise, which is exactly the fault this exercise is about.

    `seeds7.HANDOFF_SEEDS` maps each edge to the seed that breaks it.
    """
    row = dict(BY_ID[row_id])
    row["handoff_facts"] = {edge: facts}
    seed_name = seeds7.HANDOFF_SEEDS.get(edge)
    if seed_name is None:
        return {"edge": edge, "verdict": "NO SEED",
                "healthy": {"score": None, "comment": ""},
                "broken": {"score": None,
                           "comment": f"nothing in seeds7 breaks {edge!r}, so an "
                                      f"assertion on it cannot be screened. Say so "
                                      f"rather than reporting DECORATIVE."}}
    out = {}
    for seed in ("healthy", seed_name):
        res = run_pipeline(row["request"], impl="stub", seed=seeds7.get(seed))
        out[seed] = coord_eval7.handoff_integrity(res, row)
    pair = (out["healthy"]["score"], out[seed_name]["score"])
    return {"edge": edge, "seed": seed_name, "verdict": VERDICTS[pair],
            "healthy": out["healthy"], "broken": out[seed_name]}


def screen(row_id: str, spec: dict) -> dict:
    facts = {k: v for k, v in (spec.get("facts") or {}).items() if v}
    edges = [screen_edge(row_id, edge, fs) for edge, fs in facts.items()]
    # The row's verdict is its WEAKEST edge. One discriminating assertion does not
    # rescue a decorative one sitting next to it.
    order = ["WRONG", "INVERTED", "DECORATIVE", "NO SEED", "DISCRIMINATING"]
    worst = min((e["verdict"] for e in edges),
                key=lambda v: order.index(v) if v in order else 0) if edges else "WRONG"
    return {"row_id": row_id, "n_facts": sum(len(v) for v in facts.values()),
            "verdict": worst, "edges": edges,
            "predict": (spec.get("predict") or "").strip()}


def main() -> int:
    if not MY_HANDOFFS:
        print("my_handoffs7.py is empty."); return 1

    empty = [rid for rid, s in MY_HANDOFFS.items()
             if not any((s.get("facts") or {}).values())]
    if empty:
        print(f"No facts written for: {', '.join(empty)}. Open my_handoffs7.py "
              f"and fill in the TODOs.")
        if len(empty) == len(MY_HANDOFFS):
            return 1

    results = []
    for rid, spec in MY_HANDOFFS.items():
        if not any((spec.get("facts") or {}).values()):
            continue
        r = screen(rid, spec)
        results.append(r)
        print(f"\n{rid}  {r['n_facts']} fact(s) -> {r['verdict']}")
        for e in r["edges"]:
            print(f"  {e['edge']}  -> {e['verdict']}"
                  + (f"   (broken by seed: {e['seed']})" if e.get("seed") else ""))
            print(f"    healthy : {'pass' if e['healthy']['score'] else 'FAIL'}  "
                  f"{e['healthy']['comment']}")
            print(f"    broken  : {'pass' if e['broken']['score'] else 'FAIL'}  "
                  f"{e['broken']['comment']}")
        if not r["predict"]:
            # Session 5, harness bug #6: an empty prediction scored as a HIT
            # and handed every untouched TODO a perfect score. Not again.
            print("  predict : EMPTY — not scored. A prediction you did not "
                  "write cannot be wrong, which is why it is worth nothing.")
        else:
            print(f"  predict : {r['predict']}")

    disc = sum(1 for r in results if r["verdict"] == "DISCRIMINATING")
    print(f"\n{disc}/{len(results)} of your assertions discriminate.")
    if disc < len(results):
        print("An assertion that passes both runs is not a weak test. It is "
              "not a test. Ask what the receiving agent could NOT have known "
              "any other way, and assert on that.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
