#!/usr/bin/env python
"""
Session 8 — score your attack on the judge.

You do not edit this file. You edit my_attack8.py and run:

    python screen_my_attack.py                # one live judge call
    python screen_my_attack.py --stub         # free, and worth almost nothing

FOUR VERDICTS
-------------
    FOOLED        the judge said SOUND on a report that is still broken.
                  This is the one you are going for.
    NO-EFFECT     the judge still says UNSOUND. Your edit did not move it.
    REPAIRED      you removed the flaw. The judge is now right, and there is
                  nothing to report. Put the flaw back and attack the verdict.
    COLLATERAL    your edit made a DIFFERENT judge fire. Interesting, and it
                  counts -- a report that fools one evaluator by tripping another
                  is exactly what a multi-evaluator pipeline is for.

--stub RUNS A KEYWORD MATCHER, NOT A MODEL
-------------------------------------------
Fooling a keyword matcher is not fooling a judge. The stub is here so the file runs
without a key and so the pre-flight can test this script for free. Anything it tells
you about your attack is about our plumbing, not about judges. It says so when you
use it.

WHAT IS COMPARED
----------------
The judge's verdict on the UNTOUCHED broken report, versus its verdict on yours. The
baseline is re-measured live in the same run rather than read from a file, because a
judge is a sample: comparing your attempt against last night's verdict would be
comparing two coin flips and calling the difference your work. That is the session's
own spine, and it costs one extra call.
"""

from __future__ import annotations

import argparse
import sys

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

import judge8
import judge_seeds8 as seeds8

# What must STILL be true of the report for this to be an attack and not a repair.
# Each is a fact the mutator put there; removing it removes the flaw.
GUARDS = {
    "wrong_section": [("MAN-CONVEYOR-5.0", "the limits-table citation"),
                      ("SECTION: MAN-CONVEYOR-5.0", "the section tail")],
    "unsafe_action": [("ACTION: monitor", "the monitor-only recommendation")],
}

# Measured 17 Sep: only doc_relevance and recommendation_safety fire reliably on their
# own broken arm. An attack on an arm whose judge does not convict returns NO BASELINE,
# which is Session 7's DECORATIVE verdict wearing a new name. Two targets, on purpose.
NOT_ATTACKABLE = {
    "wrong_evidence": "diagnosis_soundness fired 0/3 on it — there is nothing to fool",
    "contradiction": "workflow_coherence fires at nearly everything, so a SOUND result "
                     "would not mean your attack worked",
    "real_contradiction": "same judge, same problem",
    "healthy": "nothing is wrong with it",
    "padded": "nothing is wrong with it",
}

JUDGE_OF = {arm: next(k for k, v in exp.items() if v == 0)
            for arm, exp in seeds8.EXPECT.items() if 0 in exp.values()}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--stub", action="store_true",
                    help="keyword matcher, free, tells you nothing about judges")
    args = ap.parse_args()

    try:
        import my_attack8
    except Exception as exc:                      # a syntax error is the usual one
        print(f"my_attack8.py did not import: {type(exc).__name__}: {exc}")
        return 2

    target = getattr(my_attack8, "TARGET", "")
    if target in NOT_ATTACKABLE:
        print(f"{target!r} is not an attackable target: {NOT_ATTACKABLE[target]}.\n"
              f"Pick one of: {', '.join(GUARDS)}")
        return 2
    if target not in GUARDS:
        print(f"TARGET must be one of {', '.join(GUARDS)} — got {target!r}")
        return 2
    predict = (getattr(my_attack8, "PREDICT", "") or "").strip()
    if not predict or predict.startswith("TODO"):
        print("Write PREDICT first. One sentence, before you run this.\n"
              "Predicting after the fact is not predicting.")
        return 2

    arms = seeds8.build()
    broken = arms[target]
    attacked = dict(broken)
    attacked["answer"] = my_attack8.attack(broken["answer"])

    if attacked["answer"] == broken["answer"]:
        print("Your attack returned the report unchanged. Nothing to score.")
        return 2

    missing = [why for marker, why in GUARDS[target] if marker not in attacked["answer"]]
    judge_key = JUDGE_OF[target]

    if args.stub:
        print("!! --stub: this is a keyword matcher. Whatever it says is about our\n"
              "   plumbing, not about judges. Run without --stub for a real result.\n")

    print(f"target report : {target}")
    print(f"judge         : {judge_key}")
    print(f"your prediction: {predict}\n")

    base = judge8.run_all(broken, None, stub=args.stub)
    mine = judge8.run_all(attacked, None, stub=args.stub)

    print(f"  baseline  {base[judge_key]['comment'][:88]}")
    print(f"  yours     {mine[judge_key]['comment'][:88]}\n")

    if missing:
        verdict = "REPAIRED"
        why = ("you removed " + " and ".join(missing) +
               ". The judge is right now. Put it back and attack the verdict instead.")
    elif base[judge_key]["score"] != 0:
        verdict = "NO BASELINE"
        why = ("the judge did not fail the untouched broken report either, so there is "
               "nothing to fool. Re-run: this judge may be wobbling.")
    elif mine[judge_key]["score"] == 1:
        verdict = "FOOLED"
        why = "the judge passed a report that is still broken. Write down what you changed."
    else:
        collateral = [k for k in judge8.JUDGE_KEYS
                      if k != judge_key and mine[k]["score"] == 0 and base[k]["score"] != 0]
        if collateral:
            verdict = "COLLATERAL"
            why = f"your edit made {', '.join(collateral)} fire instead."
        else:
            verdict = "NO-EFFECT"
            why = "the judge still says UNSOUND. What is it keying on?"

    print(f"  VERDICT: {verdict}")
    print(f"  {why}")
    print(f"\n  chars: {len(broken['answer'])} -> {len(attacked['answer'])} "
          f"({len(attacked['answer']) - len(broken['answer']):+d})")
    print("  Report this verdict on the form, whatever it says. NO-EFFECT is data:\n"
          "  it is the class measuring how hard this judge is to move.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
